### PR TITLE
[add] stringify arguments[0]

### PR DESCRIPTION
**Pull request by albohlabs**
If i console.t.log an object i get [object Object]. 
So i've add a JSON stringify.

### CODE REVIEW

**Comment by jgallen23** [comment]
+1

**Comment by kilianc** [comment]
+1

**Comment by kilianc** [comment]
hope to see it merged asap

**Comment by kilianc** [comment]
can you rebase this on top of the current head?

```
$ git remote add upstream git://github.com/LearnBoost/console-trace.git
$ git pull --rebase upstream master 
```

**Comment by albohlabs** [comment]
rebase done

**Comment by kilianc** [comment]
Man seriously, are you reading what you are doing?
Are you using the test suite?
Is a 3 lines pull request, sorry I stop here.

**Comment by albohlabs** [comment]
This was shit. 
Sorry, but it is too late.

**Comment by rauchg** [comment]
@kilianc what's the status on this one?

**Comment by kilianc** [comment]
we have 3 commits instead of one, but it is working, and test passes.

**Comment by rauchg** [comment]
Thanks @kilianc - you're the (trace) man

**Pull request merged**
