### PR TITLE
Finding the correct file name when removing the cwd substring

### PR DESCRIPTION
**Pull request by saambarati**
I have normalized the strings in both getFileName() and cwd() to make sure they are being compared on an even level. 

Once finding the cwd() portion of the getFileName(), I just return the original filename with the length of the cwd sliced away.

The reason I did this, was because on OS X, it wasn't removing the proper portion of the filename because the cases of each string didn't match.

### CODE REVIEW

**Comment by kilianc** [comment]
can you attach a test case please?
I can't understand how this is possible, anyway, my workspace is case sensitive,
and I am on mac, your patch is unacceptable then.

**Comment by saambarati** [comment]
It compares the strings case insensitive, because OS X doesn't destinguish between the case of a file/dir. 
I still print the file name with its correct case, just compare them the same way OS X would. 
This may not be an apt fix for most people, but it works for me. If you want It to remain case sensitive, this is especially not apt.
When I get back to my computer I will see if I can come up with a test.

**Comment by kilianc** [comment]
As I said, I work on a mac, and my workspace is case sensitive, good luck if yours is not :trollface:
I attached some code, you can overwrite the cwd option in the require call.

**Comment by saambarati** [comment]
Yeah, my hack is pretty useless bordering on dangerous if your file system is case sensitive. 
With OS X's HFS+ I believe by default is it retains the case of files, but is case insensitive in comparison. 
This can be changed though. 
I'm going to close this pull request.

**Comment by kilianc** [comment]
Anyway, you should consider to move your projects to a `Mac OS Extended (Case-sensitive, Journaled)` partition.

**Comment by saambarati** [comment]
Hey kilia, not quite sure what you mean by this?
Start my own branch?

**Comment by kilianc** [comment]
Oh no no, I was suggesting you to move your projects files (your local workspace) to a case sensitive partition

**Pull request closed without merging**
