### PR TITLE
fix bug for the callsite new api

### PR DESCRIPTION
**Pull request by numbcoder**
and update the version to 0.2.2

### CODE REVIEW

**Comment by tjmehta** [comment]
This fixed console-trace for me.

Stopped this error from occurring :::::
<project>/node_modules/console-trace/console-trace.js:43
      arguments[0] = console.traceFormat(__stack && __stack[1], name) + pad +
                                         ^
ReferenceError: __stack is not defined
    at Console.console.(anonymous function) [as error](project>/node_modules/console-trace/console-trace.js:43:42)
    at process.errors.busyHandler (<project>/lib/errors.js:16:11)
    at process.EventEmitter.emit (events.js:95:17)
    at process._fatalException (node.js:272:26)

**Comment by prabirshrestha** [comment]
+1

**Comment by andineck** [comment]
+1

**Comment by mbrevda** [comment]
+1

**Comment by andineck** [comment]
I forked, fixed and extended it: [debug-trace](https://github.com/intesso/debug-trace). would be happy to send a pull request.

**Comment by afc163** [comment]
@andi-neck :+1:

**Pull request closed without merging**
