### PR TITLE
Add option for right alignment callsite info

### PR DESCRIPTION
**Pull request by kilianc**
```
moved options in a object hash
added traceRight option
added right alignment for callsite info
```

@guille, before update the docs it would be nice to get some feedback

### CODE REVIEW

**Comment by rauchg** [comment]
I **really** like the idea of passing the options to the `require` call. I say let's remove the `trace` prefix from the options since they're already called `traceOptions`. So `traceOptions.always` for example.
Thanks!

**Comment by kilianc** [comment]
You're welcome,
Done, there is still this [annoying bug](https://github.com/LearnBoost/console-trace/pull/5), can you merge it?

**Comment by kilianc** [comment]
what we need now? :D

_p.s. sorry for the non-ff_

**Comment by rauchg** [comment]
Docs I think

**Comment by kilianc** [comment]
what do you think?
https://gist.github.com/2588858

you should upload a new terminal screenshot with tests, and send me the link

**Comment by rauchg** [comment]
Wonderful, just add a `Credits` section with your name underneath too!

**Comment by kilianc** [comment]
@guille I've done here, let's enjoy the **Cinco the Mayo** :surfer: !!

**Pull request merged**
